on:
  push:
    branches:
      - main

jobs:
  build-macos:
      strategy:
        matrix:
          arch: [x86_64, aarch64]
      
      name: ${{ matrix.arch }}
      runs-on: macos-12
      steps:
        - run: curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | bash -s -- -y
        - name: Add architecture ${{ matrix.arch }}
          run: rustup target add ${{ matrix.arch }}-apple-darwin
        - uses: actions/checkout@v4
        - name: Build application
          shell: bash
          run: |
           cd client-gui
           export COMPILE_VERSION_FILE=../target/version
           cargo build --release --target=${{ matrix.arch }}-apple-darwin
        - name: Upload artifact
          uses: actions/upload-artifact@v4
          with:
            name: ${{ matrix.arch }}-apple-darwin
            path: target/${{ matrix.arch }}-apple-darwin/release/client-gui
        - name: upload version
          uses: actions/upload-artifact@v4
          if: ${{ matrix.arch == 'aarch64'}}
          with:
            name: version
            path: target/version
        - name: Build bundler
          shell: bash
          run: |
            cd build/bundle
            cargo build --release --target=${{ matrix.arch }}-apple-darwin
        - name: Upload bundler
          uses: actions/upload-artifact@v4
          with:
            name: bundle_${{ matrix.arch }}-apple-darwin
            path: target/${{ matrix.arch }}-apple-darwin/release/bundle


  windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build
        run: |
          rustup target add x86_64-pc-windows-msvc
          cargo build --release --target x86_64-pc-windows-msvc

      - uses: actions/upload-artifact@v4
        with:
          name: x86_64-pc-windows-msvc
          path: target/x86_64-pc-windows-msvc/release/client-gui.exe

  universal-binary:
    name: Build DMG
    needs: [build-macos, windows]
    runs-on: macos-12
    steps:
      - uses: actions/checkout@v4
      - name: Download x86_64
        uses: actions/download-artifact@v4
        with:
          name: x86_64-apple-darwin
          path: x86_64-apple-darwin
      - name: Download arm64
        uses: actions/download-artifact@v4
        with:
          name: aarch64-apple-darwin
          path: aarch64-apple-darwin
      - name: Combine app bundles
        shell: bash
        run: |
          brew install create-dmg
          export X86_64_APPLE_DARWIN=x86_64-apple-darwin/client-gui
          export AARCH64_APPLE_DARWIN=aarch64-apple-darwin/client-gui
          export DMG_OUTPUT_PATH=CraftIP.dmg
          sh build/build-mac.sh
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: CraftIP.dmg
          path: CraftIP.dmg

      - name: Download windows
        uses: actions/download-artifact@v4
        with:
          name: x86_64-pc-windows-msvc
          path: x86_64-pc-windows-msvc




      - name: Download version
        uses: actions/download-artifact@v4
        with:
          name: version
          path: version

      - name: Combine app bundles
        shell: bash
        run: |
          mkdir -p bundle/bin
          cp x86_64-apple-darwin/client-gui bundle/bin/x86_64-apple-darwin
          cp aarch64-apple-darwin/client-gui bundle/bin/aarch64-apple-darwin
          cp x86_64-pc-windows-msvc/client-gui.exe bundle/bin/x86_64-pc-windows-msvc
          cp version/version bundle/version
          
          mkdir bundle/downloads
          cp CraftIP.dmg bundle/downloads/CraftIP.dmg
          cp x86_64-pc-windows-msvc/client-gui.exe bundle/downloads/CraftIP.exe
      - name: upload bundle
        uses: actions/upload-artifact@v4
        with:
          name: bundle
          path: bundle
